### PR TITLE
Minor edits to paper.md

### PR DESCRIPTION
**Pull request by kyleniemeyer**

### CODE REVIEW

**Comment by matbesancon** [comment]
Hi, thanks for the suggestion, the formatting is made so to correspond to the one required by JOSS.

**Comment by matbesancon** [comment]
@kyleniemeyer the square brackets are required I believe no? Can you remove these and I'll merge for the `e.g.,`

**Comment by kyleniemeyer** [comment]
Hi @matbesancon, the square brackets are not explicitly required, but used for parenthetical references.

From our documentation:
> For a quick reference, the following citation commands can be used:
>- `@author:2001`  ->  "Author et al. (2001)"
>- `[@author:2001]` -> "(Author et al., 2001)"
>- `[@author1:2001; @author2:2001]` -> "(Author1 et al., 2001; Author2 et al., 2002)"

So doing the `@author:2001` format will put the author name in the sentence as a first-class object, with the year in parentheses. This is consistent with the other copy-edits I did.

**Comment by matbesancon** [comment]
Oh got it, thanks

**Pull request merged**
